### ISSUE TITLE
Start working on this

### ISSUE THREAD

**Issue by StevenCopeland** [hiddencodecademy/Introduction#3]
@CodecademyHiddenCourses/employees We need to start working on this repo to. Can I get a group to work on this?

**Comment by SoldierCorp** [comment]
Hi,

What's the goal of this repository?

**Comment by StevenCopeland** [comment]
@SoldierCorp to find hidden courses.

**Comment by nicolaihoilund** [comment]
Why is that necessary? Isn't that what the other repo is for? Am I missing something?

**Comment by StevenCopeland** [comment]
@nicolaihoilund 

1. It is not necessary. Not many things are.
2. There are no other repos that I could find for this.
3. I doubt you are missing something.

@SoldierCorp 

Sorry, I thought you where asking what was the whole purpose of the org.

The purpose of this repo is to tell the contributors how to do add and how to contribute to the courses repo.

**Comment by nicolaihoilund** [comment]
I think we should use the dedicated wiki for that.

**Comment by StevenCopeland** [comment]
@nicolaihoilund I am not sure what you mean. :confused:

**Comment by nicolaihoilund** [comment]
https://github.com/CodecademyHiddenCourses/Courses/wiki

**Comment by StevenCopeland** [comment]
@nicolaihoilund That is probably a good idea. But not many people look at the wiki....

**Comment by SoldierCorp** [comment]
In my opinion, the wiki is for those projects in which the user needs to read first before to use it or when something is complicated to understand, but in this case we only need to set some instructions to the readme file to specify the steps the user needs to follow for the setup or contributions.

**Comment by nicolaihoilund** [comment]
It was just a suggestion. A whole new repository for some simple instructions are way to overkill.
Also, when you have documentation (in general) in the wiki, you would mention it in the readme, issue or wherever and link to it. 

The simplest approach is just to write some instructions in the readme, where people will land anyways if they want to help out.

**Comment by nicolaihoilund** [comment]
Would you be able to rename the organization to "hiddencodecademy"? Then rename the main repo to "hiddencodecademy.github.io". Then we will be able to use http://hiddencodecademy.github.io/. Looks cleaner and is easier to remember.

**Comment by nicolaihoilund** [comment]
Rename the main repo to "hiddencodecademy.github.io". Github Pages will use that as the address instead of "hiddencodecademy.github.io/Courses".

**Comment by nicolaihoilund** [comment]
Thank you. Looooks soo much nicer https://hiddencodecademy.github.io/

Now, I think you should close this repo.
I'll create an issue about writing the guide on how to add a course.
